DONORS = [
    {
        "id": "donor-sf-a-pos",
        "name": "Maya Patel",
        "type": "individual",
        "blood_group": "A",
        "rhd": "positive",
        "zipcode": "94103",
        "latitude": 37.7749,
        "longitude": -122.4194,
        "email": "maya.patel@example.com",
        "phone": "+14155550101",
        "preferences": {"email": True, "phone": False, "sms": True},
        "availability": "Available today",
    },
    {
        "id": "donor-sf-o-neg",
        "name": "Jordan Lee",
        "type": "individual",
        "blood_group": "O",
        "rhd": "negative",
        "zipcode": "94110",
        "latitude": 37.7486,
        "longitude": -122.4184,
        "email": "jordan.lee@example.com",
        "phone": "+14155550102",
        "preferences": {"email": True, "phone": True, "sms": False},
        "availability": "Available within 2 hours",
    },
    {
        "id": "donor-oak-b-pos",
        "name": "Sam Rivera",
        "type": "individual",
        "blood_group": "B",
        "rhd": "positive",
        "zipcode": "94612",
        "latitude": 37.8044,
        "longitude": -122.2712,
        "email": "sam.rivera@example.com",
        "phone": "+15105550103",
        "preferences": {"email": False, "phone": False, "sms": True},
        "availability": "Available tomorrow",
    },
    {
        "id": "hospital-general-ab-pos",
        "name": "Bay Regional Hospital",
        "type": "hospital",
        "blood_group": "AB",
        "rhd": "positive",
        "zipcode": "94115",
        "latitude": 37.7864,
        "longitude": -122.4378,
        "email": "blooddesk@bayregional.example.org",
        "phone": "+14155550104",
        "preferences": {"email": True, "phone": True, "sms": False},
        "availability": "Emergency intake open",
    },
    {
        "id": "hospital-east-o-pos",
        "name": "East Bay Civic Blood Center",
        "type": "hospital",
        "blood_group": "O",
        "rhd": "positive",
        "zipcode": "94607",
        "latitude": 37.7955,
        "longitude": -122.2790,
        "email": "requests@eastbayblood.example.org",
        "phone": "+15105550105",
        "preferences": {"email": True, "phone": True, "sms": True},
        "availability": "Critical shortage partner",
    },
    {
        "id": "donor-sj-a-neg",
        "name": "Avery Chen",
        "type": "individual",
        "blood_group": "A",
        "rhd": "negative",
        "zipcode": "95112",
        "latitude": 37.3387,
        "longitude": -121.8853,
        "email": "avery.chen@example.com",
        "phone": "+14085550106",
        "preferences": {"email": True, "phone": False, "sms": False},
        "availability": "Available this week",
    },
    {
        "id": "donor-sf-ab-neg",
        "name": "Priya Shah",
        "type": "individual",
        "blood_group": "AB",
        "rhd": "negative",
        "zipcode": "94107",
        "latitude": 37.7618,
        "longitude": -122.3986,
        "email": "priya.shah@example.com",
        "phone": "+14155550107",
        "preferences": {"email": False, "phone": True, "sms": True},
        "availability": "Available after 5 PM",
    },
    {
        "id": "donor-berkeley-o-pos",
        "name": "Noah Williams",
        "type": "individual",
        "blood_group": "O",
        "rhd": "positive",
        "zipcode": "94704",
        "latitude": 37.8719,
        "longitude": -122.2585,
        "email": "noah.williams@example.com",
        "phone": "+15105550108",
        "preferences": {"email": True, "phone": False, "sms": True},
        "availability": "Available today",
    },
    {
        "id": "donor-daly-b-neg",
        "name": "Elena Garcia",
        "type": "individual",
        "blood_group": "B",
        "rhd": "negative",
        "zipcode": "94015",
        "latitude": 37.6879,
        "longitude": -122.4702,
        "email": "elena.garcia@example.com",
        "phone": "+16505550109",
        "preferences": {"email": True, "phone": True, "sms": True},
        "availability": "Available within 4 hours",
    },
    {
        "id": "donor-palo-alto-ab-pos",
        "name": "Marcus Johnson",
        "type": "individual",
        "blood_group": "AB",
        "rhd": "positive",
        "zipcode": "94301",
        "latitude": 37.4419,
        "longitude": -122.1430,
        "email": "marcus.johnson@example.com",
        "phone": "+16505550110",
        "preferences": {"email": False, "phone": False, "sms": False},
        "availability": "Profile visible, contact disabled",
    },
    {
        "id": "hospital-south-a-neg",
        "name": "South Bay Emergency Hospital",
        "type": "hospital",
        "blood_group": "A",
        "rhd": "negative",
        "zipcode": "95128",
        "latitude": 37.3161,
        "longitude": -121.9352,
        "email": "bloodbank@southbayemergency.example.org",
        "phone": "+14085550111",
        "preferences": {"email": True, "phone": True, "sms": False},
        "availability": "Accepting urgent requests",
    },
    {
        "id": "hospital-peninsula-b-pos",
        "name": "Peninsula Regional Medical Center",
        "type": "hospital",
        "blood_group": "B",
        "rhd": "positive",
        "zipcode": "94403",
        "latitude": 37.5446,
        "longitude": -122.3051,
        "email": "coordination@peninsularegional.example.org",
        "phone": "+16505550112",
        "preferences": {"email": True, "phone": False, "sms": True},
        "availability": "Regional shortage coordinator",
    },
    {
        "id": "hospital-marin-o-neg",
        "name": "Marin Civic Health Network",
        "type": "hospital",
        "blood_group": "O",
        "rhd": "negative",
        "zipcode": "94901",
        "latitude": 37.9735,
        "longitude": -122.5311,
        "email": "donorline@marincivic.example.org",
        "phone": "+14155550113",
        "preferences": {"email": True, "phone": True, "sms": True},
        "availability": "O-negative emergency desk",
    },
]
